services:
  - type: web
    name: estimate_moving_price
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:api --host 0.0.0.0 --port $PORT"
    healthCheckPath: /healthz
